### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by luser** [rbspy/read-process-memory#11]
Now that Travis CI has ended their free tier, CI should migrate to GitHub Actions. [The `actions-rs` quickstart example](https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md) is probably a good place to start.

**Comment by benfred** [comment]
Fwiw - see https://github.com/benfred/read-process-memory/pull/5 that switches to using github actions (and fixes the broken macos unittest0.

Feel free to use anything useful you see there - my fork has diverged enough because of #6/#7 etc that this isn't directly merge-able but should be pretty easy to tweak to use here.

**Comment by luser** [comment]
Oh, cool, thanks! Would you be interested in me adding you as a collaborator on this repo + crate author on crates.io, and merging your changes here? I've been a bit lax in maintaining some of my crates and if you're actively invested in it I'm happy to let you take over. I'd also be happy to provide occasional code review and such if you're into that.

**Comment by acj** [comment]
+1 to merging the changes so that we have a single home for this code again. It's currently a bit confusing trying to find the most up-to-date shipping version, deciding where to submit bug fixes, etc. The best option seems to be Ben's fork, which has several useful fixes already, but the current shipping version is in a branch/PR. Given that the different variants of this crate are load-bearing for several prominent projects (py-spy, rbspy, etc), I think it would be nice to consolidate the effort.

I'll also offer the rbspy org (the ancestral home of this code, IIUC? :-)) as a home if that would ease the maintenance burden. We have a handful of related projects there. No pressure, though.

**Comment by luser** [comment]
> I'll also offer the rbspy org (the ancestral home of this code, IIUC? :-)) as a home if that would ease the maintenance burden. We have a handful of related projects there. No pressure, though.

I did in fact start this project (with the blessing of the rbspy authors) by pulling the code from there and adding a Windows implementation. :) I'd be happy to migrate the repo there and add the org to the crates.io author list to allow ongoing maintenance if that would make people's lives easier.

**Comment by acj** [comment]
@luser Did you have any luck adding the maintainers team to crates.io? If not, feel free to add me directly, and then I'll try to add the owners team.

**Comment by luser** [comment]
That worked, thanks!
https://crates.io/crates/read-process-memory

Feel free to publish new versions as needed. I'm happy to advise or review changes as needed, thanks everyone for taking on shared maintenance!

**Comment by acj** [comment]
Looks like we're good -- 0.1.3 is published. The crates.io web UI doesn't let me do anything with read-process-memory, but I'm able to publish using cargo. Not a problem, just unexpected.

Thanks, all!
